//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tools.
        /// </summary>
        internal static string AllTools {
            get {
                return ResourceManager.GetString("AllTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Tools.
        /// </summary>
        internal static string ExperimentalTools {
            get {
                return ResourceManager.GetString("ExperimentalTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQueryUI, Facebook, Google Plus , ....
        /// </summary>
        internal static string ExperimentalToolsNote {
            get {
                return ResourceManager.GetString("ExperimentalToolsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Tools.
        /// </summary>
        internal static string FinishedTools {
            get {
                return ResourceManager.GetString("FinishedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website has been made just for evaluation of new technologies..
        /// </summary>
        internal static string HomePageMessage {
            get {
                return ResourceManager.GetString("HomePageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page..
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location on Google map..
        /// </summary>
        internal static string MapNote {
            get {
                return ResourceManager.GetString("MapNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS.
        /// </summary>
        internal static string RSS {
            get {
                return ResourceManager.GetString("RSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read RSS.
        /// </summary>
        internal static string RSSNote {
            get {
                return ResourceManager.GetString("RSSNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Information.
        /// </summary>
        internal static string ServerInformation {
            get {
                return ResourceManager.GetString("ServerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your files in web server and access them form everywhere..
        /// </summary>
        internal static string UploadNote {
            get {
                return ResourceManager.GetString("UploadNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system information, including your screen size and location..
        /// </summary>
        internal static string UserInformationNote {
            get {
                return ResourceManager.GetString("UserInformationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weblog.
        /// </summary>
        internal static string Weblog {
            get {
                return ResourceManager.GetString("Weblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your ideas..
        /// </summary>
        internal static string WeblogNote {
            get {
                return ResourceManager.GetString("WeblogNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebTools.
        /// </summary>
        internal static string WebTools {
            get {
                return ResourceManager.GetString("WebTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS, Ping, Search , ....
        /// </summary>
        internal static string WebToolsNote {
            get {
                return ResourceManager.GetString("WebToolsNote", resourceCulture);
            }
        }
    }
}
